// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationCenter.Data.Models;

public partial class Assignment
{
    public int AssignmentID { get; set; }

    public int? SectionID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? DueDate { get; set; }

    public int? MaxScore { get; set; }

    public virtual ClassSection Section { get; set; }

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}