// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationCenter.Data.Models;

public partial class Attendance
{
    public int AttendanceID { get; set; }

    public int? SectionID { get; set; }

    public int? StudentID { get; set; }

    public DateOnly? Date { get; set; }

    public string Status { get; set; }

    public virtual ClassSection Section { get; set; }

    public virtual Student Student { get; set; }
}