// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationCenter.Data.Models;

public partial class ClassSection
{
    public int SectionID { get; set; }

    public int? CourseID { get; set; }

    public int? TeacherID { get; set; }

    public string Semester { get; set; }

    public int? Year { get; set; }

    public string Schedule { get; set; }

    public string Room { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual Course Course { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual Teacher Teacher { get; set; }
}