// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationCenter.Data.Models;

public partial class Course
{
    public int CourseID { get; set; }

    public string CourseCode { get; set; }

    public string CourseName { get; set; }

    public string Description { get; set; }

    public int? Credits { get; set; }

    public int? DepartmentID { get; set; }

    public virtual ICollection<ClassSection> ClassSections { get; set; } = new List<ClassSection>();

    public virtual Department Department { get; set; }
}