// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EducationCenter.Data.Models;

public partial class EducationCenterContext : DbContext
{
    public EducationCenterContext(DbContextOptions<EducationCenterContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<Attendance> Attendances { get; set; }

    public virtual DbSet<ClassSection> ClassSections { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Enrollment> Enrollments { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Submission> Submissions { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentID).HasName("PK__Assignme__32499E57B697CA4D");

            entity.Property(e => e.Title).HasMaxLength(150);

            entity.HasOne(d => d.Section).WithMany(p => p.Assignments)
                .HasForeignKey(d => d.SectionID)
                .HasConstraintName("FK__Assignmen__Secti__4E88ABD4");
        });

        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.HasKey(e => e.AttendanceID).HasName("PK__Attendan__8B69263C67D6C76B");

            entity.ToTable("Attendance");

            entity.Property(e => e.Status).HasMaxLength(10);

            entity.HasOne(d => d.Section).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.SectionID)
                .HasConstraintName("FK__Attendanc__Secti__5535A963");

            entity.HasOne(d => d.Student).WithMany(p => p.Attendances)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK__Attendanc__Stude__5629CD9C");
        });

        modelBuilder.Entity<ClassSection>(entity =>
        {
            entity.HasKey(e => e.SectionID).HasName("PK__ClassSec__80EF089274CA73B4");

            entity.Property(e => e.Room).HasMaxLength(50);
            entity.Property(e => e.Schedule).HasMaxLength(100);
            entity.Property(e => e.Semester).HasMaxLength(50);

            entity.HasOne(d => d.Course).WithMany(p => p.ClassSections)
                .HasForeignKey(d => d.CourseID)
                .HasConstraintName("FK__ClassSect__Cours__440B1D61");

            entity.HasOne(d => d.Teacher).WithMany(p => p.ClassSections)
                .HasForeignKey(d => d.TeacherID)
                .HasConstraintName("FK__ClassSect__Teach__44FF419A");
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CourseID).HasName("PK__Courses__C92D71873936164D");

            entity.HasIndex(e => e.CourseCode, "UQ__Courses__FC00E0008F3C0D17").IsUnique();

            entity.Property(e => e.CourseCode).HasMaxLength(50);
            entity.Property(e => e.CourseName).HasMaxLength(150);
            entity.Property(e => e.Description).HasMaxLength(255);

            entity.HasOne(d => d.Department).WithMany(p => p.Courses)
                .HasForeignKey(d => d.DepartmentID)
                .HasConstraintName("FK__Courses__Departm__412EB0B6");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentID).HasName("PK__Departme__B2079BCD879F033B");

            entity.Property(e => e.DepartmentName).HasMaxLength(150);
            entity.Property(e => e.Description).HasMaxLength(255);
        });

        modelBuilder.Entity<Enrollment>(entity =>
        {
            entity.HasKey(e => e.EnrollmentID).HasName("PK__Enrollme__7F6877FBE003F473");

            entity.Property(e => e.Grade).HasMaxLength(5);

            entity.HasOne(d => d.Section).WithMany(p => p.Enrollments)
                .HasForeignKey(d => d.SectionID)
                .HasConstraintName("FK__Enrollmen__Secti__48CFD27E");

            entity.HasOne(d => d.Student).WithMany(p => p.Enrollments)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK__Enrollmen__Stude__47DBAE45");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentID).HasName("PK__Payments__9B556A5847B3028E");

            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.ReferenceNumber).HasMaxLength(100);

            entity.HasOne(d => d.Student).WithMany(p => p.Payments)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK__Payments__Studen__59FA5E80");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentID).HasName("PK__Students__32C52A790AA730C2");

            entity.HasIndex(e => e.Email, "UQ__Students__A9D1053416DEF614").IsUnique();

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(15);
            entity.Property(e => e.Status).HasMaxLength(20);
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.HasKey(e => e.SubmissionID).HasName("PK__Submissi__449EE105C9350679");

            entity.Property(e => e.FilePath).HasMaxLength(255);
            entity.Property(e => e.SubmissionDate).HasColumnType("datetime");

            entity.HasOne(d => d.Assignment).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.AssignmentID)
                .HasConstraintName("FK__Submissio__Assig__5165187F");

            entity.HasOne(d => d.Student).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.StudentID)
                .HasConstraintName("FK__Submissio__Stude__52593CB8");
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.HasKey(e => e.TeacherID).HasName("PK__Teachers__EDF25944A6760983");

            entity.HasIndex(e => e.Email, "UQ__Teachers__A9D1053460F7FA63").IsUnique();

            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.Phone).HasMaxLength(15);

            entity.HasOne(d => d.Department).WithMany(p => p.Teachers)
                .HasForeignKey(d => d.DepartmentID)
                .HasConstraintName("FK__Teachers__Depart__3D5E1FD2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}