// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationCenter.Data.Models;

public partial class Enrollment
{
    public int EnrollmentID { get; set; }

    public int? StudentID { get; set; }

    public int? SectionID { get; set; }

    public DateOnly? EnrollmentDate { get; set; }

    public string Grade { get; set; }

    public virtual ClassSection Section { get; set; }

    public virtual Student Student { get; set; }
}