// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationCenter.Data.Models;

public partial class Submission
{
    public int SubmissionID { get; set; }

    public int? AssignmentID { get; set; }

    public int? StudentID { get; set; }

    public DateTime? SubmissionDate { get; set; }

    public int? Score { get; set; }

    public string FilePath { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual Student Student { get; set; }
}